[project]
name = "odoo-addons-oca-fleet"
version = "19.0.20260209.0"
dependencies = [
    "odoo-addon-fleet_vehicle_category==19.0.*",
    "odoo-addon-fleet_vehicle_fuel_type_ethanol==19.0.*",
    "odoo-addon-fleet_vehicle_inspection==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
